config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :comments
  end

  root "places#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @place = Place.find(params[:place_id])
    @comment = @place.comments.create(comment_params)
    redirect_to place_path(@place)
	end

	def destroy
    @place = Place.find(params[:place_id])
    @comment = @place.comments.find(params[:id])
    @comment.destroy
    redirect_to place_path(@place)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :text, :reference)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@places = Place.all
	end
	
	def show
		@place = Place.find(params[:id])
	end

	def new
  		@place = Place.new
	end

	def edit
		@place = Place.find(params[:id])
	end
 
	def create
  		@place = Place.new(place_params)
 
  		if @place.save
    		redirect_to @place
  		else
    		render 'new'
  		end
	end

	def update
		@place = Place.find(params[:id])

		if @place.update(place_params)
			redirect_to @place
		else
			render 'edit'
		end
	end

	def destroy
		@place = Place.find(params[:id])
		@place.destroy

		redirect_to places_path
	end
 
	private
  		def place_params
    	params.require(:place).permit(:name, :address, :rating)
  		end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
	<p>
	  <strong>Commenter:</strong>
	  <%= comment.commenter %>
	</p>
	 
	<p>
	  <strong>Text:</strong>
	  <%= comment.text %>
	</p>
	<p>
	  <strong>Reference:</strong>
	  <%= comment.reference %>
	</p>
</div>
<p>
  <%= link_to 'Destroy Comment', [comment.place, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@place, @place.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
   <p>
    <%= f.label :reference %><br>
    <%= f.text_area :reference %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LekkerPlekke</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
 
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@place.errors.count, "error") %> prohibited
        this place from being saved:
      </h2>
      <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.label :rating %><br>
    <%= f.select :rating, ["1", "2", "3", "4", "5"] %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/places/edit.html.erb
<h1>Edit place</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing Places</h1>
<%= link_to 'New place', new_place_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Rating</th>
    <th colspan="3"></th>
  </tr>
 
  <% @places.each do |place| %>
    <tr>
      <td><%= place.name %></td>
      <td><%= place.address %></td>
      <td><%= place.rating %></td>
      <td><%= link_to 'Show', place_path(place) %></td>
      <td><%= link_to 'Edit', edit_place_path(place) %></td>
      <td><%= link_to 'Destroy', place_path(place),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/places/new.html.erb
<h1>New place</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Place</h1>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @place.rating %>
</p>

<hr><br>

<h2>Comments</h2>
<%= render @place.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>